---
root: true
env:
  amd: true
  browser: true
globals:
  module: true
  require: true
  ga: true
  NLX: true
extends: eslint:recommended
rules:
  array-bracket-spacing:
    - error
    - always
    - singleValue: false
      objectsInArrays: false
      arraysInArrays: false
  block-scoped-var:
    - error
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: false
  comma-dangle:
    - error
    - never
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  curly:
    - error
  eol-last:
    - error
  eqeqeq:
    - error
    - always
  indent:
    - error
    - 2
  keyword-spacing:
    - error
    - before: true
      after: true
  linebreak-style:
    - error
    - unix
  newline-after-var:
    - error
    - always
  no-multi-spaces:
    - error
  no-nested-ternary:
    - error
  no-trailing-spaces:
    - error
  no-whitespace-before-property:
    - error
  object-curly-spacing:
    - error
    - always
    - arraysInObjects: true
      objectsInObjects: true
  one-var:
    - error
    - never
  radix:
    - error
    - always
  quotes:
    - error
    - single
  semi:
    - error
    - always
  semi-spacing:
    - error
    - after: true
      before: false
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - always
    - exceptions:
      - "{}"
      - "[]"
  space-infix-ops:
    - error
  space-unary-ops:
    - error
    - nonwords: false
      words: true
  vars-on-top:
    - error
