---
linters:
  BangFormat:
    space_before_bang: true
    space_after_bang: false
  BemDepth:
    enabled: false
  BorderZero:
    enabled: true
    convention: none
  ChainedClasses:
    enabled: true
  ColorKeyword:
    enabled: true
    severity: warning
  ColorVariable:
    enabled: true
  Comment:
    enabled: true
  DebugStatement:
    enabled: true
  DeclarationOrder:
    enabled: true
  DisableLinterReason:
    enabled: false
  DuplicateProperty:
    enabled: true
    ignore_consecutive:
      - background
  ElsePlacement:
    enabled: true
    style: new_line
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
  EmptyRule:
    enabled: true
  ExtendDirective:
    enabled: true
  FinalNewline:
    enabled: false # not a job for the linter
    present: true
  HexLength:
    enabled: false
  HexNotation:
    enabled: true
    style: lowercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: true
  ImportantRule:
    enabled: true
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
  Indentation:
    enabled: false # not a job for the linter
    allow_non_nested_indentation: false
    character: space
    width: 2
  LeadingZero:
    enabled: true
    style: exclude_zero
  LengthVariable:
    enabled: false # otherwise quite restrictive
    allowed_lengths:
      -
    allowed_properties:
      -
  MergeableSelector:
    enabled: true
    force_nesting: false
    whitelist:
  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: camel_case
  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false
  PlaceholderInExtend:
    enabled: true
  PrivateNamingConvention:
    enabled: true
    prefix: _
  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 10
  PropertySortOrder:
    enabled: true
    ignore_unspecified: true
    min_properties: 4
    order:
      - top
      - right
      - bottom
      - left
    separate_groups: true
  PropertySpelling:
    enabled: true
    extra_properties:
      -
    disabled_properties:
      - zoom
  PropertyUnits:
    # global: by default any unit is allowed
    properties:
      # don't allow ems for borders as they disappear in Safari
      border:
        - px
      # don't allow units for line-height
      line-height:
        -
  PseudoElement:
    enabled: true
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false
  SelectorDepth:
    enabled: true
    max_depth: 3
  SelectorFormat:
    enabled: false
    convention: hyphenated_lowercase
    ignored_names:
      -
    ignored_types:
      -
  Shorthand:
    enabled: true
    allowed_shorthands:
      - 1
      - 2
      - 3
      - 4
  SingleLinePerProperty:
    enabled: true;
    allow_single_line_rule_sets: false
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
    style: one_space
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  SpaceAfterPropertyName:
    enabled: true
  SpaceAfterVariableColon:
    enabled: true
    style: one_space
  SpaceAfterVariableName:
    enabled: true
  SpaceAroundOperator:
    enabled: true
    style: one_space
  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false
    style: space
  SpaceBetweenParens:
    enabled: true
    spaces: 1
  StringQuotes:
    enabled: true
    style: single_quotes
  TrailingSemicolon:
    enabled: true
  TrailingWhitespace:
    enabled: false # not a job for the linter
  TrailingZero:
    enabled: true
  TransitionAll:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VariableForProperty:
    enabled: true
    properties:
      - color
  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers:
      -
    excluded_identifiers:
      -
  ZeroUnit:
    enabled: true;
