#!/bin/bash
# Use this script to run the makefile within a docker container

AWS_CREDS_DIR="$HOME/.aws"
DOCKER_PROJECT_DIR="/nlx"
IMG_NAME="auth0-custom-lock-builder"
HUB="mozillaiam"
CONTAINER_NAME="$IMG_NAME-container"

function usage() {
  echo "Build make targets in a container (${IMG_NAME})"
  echo "$0 make <make target>"
  exit 127
}

function check_img() {
  docker image ls ${IMG_NAME} 2>&1 > /dev/null && return 0
  echo "Cannot find docker image ${IMG_NAME}."
  echo "Please run \`make dkrbuild\` to build it, or \`docker pull ${HUB}/${IMG_NAME}\`".
  return 1
}

[[ $# -eq 0 ]] && usage

check_img || exit 127

exec docker run --rm --name ${CONTAINER_NAME} \
  -u $(id -u) \
  -v ${AWS_CREDS_DIR}:/root/.aws \
  -v $(pwd):${DOCKER_PROJECT_DIR} \
  ${IMG_NAME}:latest make $@
